#!/bin/bash

# 打印命令

# 打印文本的小写 p 命令

# 打印行号的 (=) 号命令

# 列出行的 l 命令


# -n 选项禁止其他行，仅仅包括模式匹配到的行
sed -n '/3/p' test2

echo

# 也可以范围搜索

sed -n '2,3p' test2


echo
# 打印行号

sed '=' test2

echo 
 
# 列出行 显示数据流中不可打印的ASCII字符
sed -n 'l' test2

