#!/bin/bash


# 写文件 ： [address]w filename

# 将 test2 的前两行写入  test3
sed '1,2w test3' test2


sed -n '/7/w test3' test2

echo
# 从文件读取数据 : [address]r filename (不能使用范围指定)

# 把 test3 的数据  添加到 test2 的第二行后
sed '2r test3' test2

echo 
# 模式匹配
sed '/7/r test3' test2


echo

# 添加到末尾  : $ 符号
sed '$r test3' test2



echo
# 使用占位符 替换

sed  '/LIST/{$r test3;d}' test2

