#!/bin/bash

clear

# 与分支命令类似，测试命令(t)也用于更改编辑器脚本的流程；测试命令不是基于地址跳转到标签，二十基于替换命令的结果跳转到标签

# 如果替换命令成功匹配并且替换了一个模式，则测试命令分支到指定标签；如果替换命令不匹配指定的模式，则测试命令不分支

# 测试命令与分支命令有相同的格式  ： [address]t [label]

# 如果不指定标签，则测试成功时sed将分支到最后

# 测试命令为在数据流文本上执行基本的 if-then 语句提供了一种简单方式


# 第一个替换命令匹配成功执行对应替换； 不成功执行t之后的命令

sed '{
s/header/start/;
t;
s/line/test/
}' test


echo

# 改进循环

echo 'This, is, a, test, to, remove, commas' | sed -n '{
:start;
s/,/--/1p;
t start
}'



