#!/bin/bash

# trapping the script exit


# echo bitch fuck when current script exit
trap "echo  bitch fuck" EXIT

count=1

while [ $count -le 5 ]
do
  echo 
  echo "Loop #$count"
  sleep 1
  count=$[ $count + 1 ]
done
