#!/bin/bash


trap "echo  bitch fuck" EXIT

count=1

while [ $count -le 5 ]
do
  echo 
  echo "Loop #$count"
  sleep 1
  count=$[ $count + 1 ]
done

# remove trap

trap - EXIT

echo 
echo "i have remove the trapping"
~     
