#!/bin/bash

echo "SIGHUP -> 1 hang up process"

echo

echo "SIGINT -> 2 interrupt process"

echo 

echo "SIGQUIT -> 3 stop process"

echo 

echo "SIGKILL -> 9 uncondictional kill process"

echo

echo "SIGTERM -> 15 if it is prossible to kill  process temporary"

echo 

echo "SIGSTOP -> 17 uncondictional stop process no kill"

echo 


echo "SIGTSTP -> 18 stop or suspend process"

echo

echo "SIGCONT -> 19 restart process that was stopped "





echo

echo "Ctrl + C  -> SIGINT  "

echo 

echo "Ctrl + Z -> SIGTSTP"


echo 

echo "kill -> SIGKILL"







