#!/bin/bash

# simple script menu


function diskspace {
  clear
  df -k
}


function whoseon {
  clear
  who
}


function memusage {
  clear
  cat /proc/meminfo
}



# menu function
function menu {
 clear

 echo

 echo -e "\tSys Admin Menu\n"
 echo -e "\t1. Display disk space"
 echo -e "\t2. Display logged on users"
 echo -e "\t3. Display memory  usage"
 echo -e "\t0. Exit Menu\n\n"
 # -en show current ling but not wrap
 echo -en "\tEnter option :"

 read -n 1 option
}



# logical
while [ 1 ]
do
 menu

 case $option in
 0) 
   break;;
 1)
   diskspace;;
 2)
   whoseon;;
 3)
   memusage;;
 *)
   clear
   echo "Sorry, wrong select";;
 esac

echo -en "\n\n\t\t\tHit any key to continue"
read -n 1 line
done















