#!/bin/bash

clear

# 特殊字符类

# 匹配任意字母 大写或者小写 A-Z a-z  ：  [[:alpha:]]

# 匹配任意字符数字  A-Z a-z 0-9 : [[:alnum:]]

# 空格或制表符 ： [[:blank:]]

# 匹配0-9的数字 ： [[:digit:]]

# 任意小写字符a-z ： [[:lower:]]

# 任意可以打印的字符 ： [[:print:]]

# 匹配标点符号 ： [[:punct:]]

# 匹配任意空白符 空格  制表符 NL FF VT CR ： [[:space:]]

# 匹配任意大写字母 ： [[:upper:]]
