#!/bin/bash

# notice
# 1: if Cencel and No is availd, need to check exit status
# 2: redirect STDERR(2) to get output


# example
temp=`mktemp -t test.XXX`
temp2=`mktemp -t test2.XXX`

function diskspace {
 df -k > $temp
 
 dialog --textbox $temp 20 60 
}


function whoseon {
  who > $temp
  dialog --textbox $temp 20 50
}

function memusage {
  cat /proc/meminfo > $temp
  
  dialog --textbox $temp 20 50
}

while [ 1 ]
do
  dialog --menu "Sys Admin Menu" 20 30 10 1 "Display disk space" 2 "Display users" 3 "Display memory usage" 4 "Exit" 2>$temp2
  
  if [ $? -eq 1 ]
   then
    break
  fi
  

  sel=`cat $temp2` 
  case $sel in 
  1) 
   diskspace;;
  2)
   whoseon;;
  3)
   memusage;;
  4) 
   break;;
  *)
   dialog --msgbox "Soory ,invalid selection " 10 30
  esac
done

rm -f $temp 2> /dev/null
rm -f $temp2 2> /dev/null
































