#!/bin/bash

# save order`s result to a file

# '>'  cover file content

date > /tmp/shell/tmp/test

# '>>' add file content

pwd >> /tmp/shell/tmp/test


# '<' input file content to a command
wc < /tmp/shell/tmp/test

# '<<'  
wc << EOF
>test1
>test3
>test3
> EOF

