#!/bin/bash

# to show how to use variable

# environment variable
# show all environment variable
set 

echo UID:$UID
echo HOME:$HOME


# user define variable
var1=123
var2=dream
var3="fuck"

echo "$var1 + $var2 + $var3"

var1=456

# notice when to assignment a value to user variable don`t  need '$' ;  when use the user variable need '$'
var5=$var2

echo $var1
echo $var5
