#!/bin/bash


# Postfix 系统由若干个邮件队列目录和可执行程序构成
# Postfix 包使用始终运行在后台的master进程
# 主程序允许Postfix产生程序以描述新消息的邮件队列并将它们发送到适当的地址
# 在装备核心程序后，可以将其配置为在设置时间运行
# 主程序用于控制Postfix的所有操作，它负责开启需要开启的其他Postfix进程
# qmgr 和  pickup程序被配置为比其他核心程序停驻时间更长的后台进程
# qmgr 负责Postfix的中心消息路由系统
# pickup决定消息何时可供Postfix系统发送

