#!/bin/bash

# 什么是正则表达式

# 数据流 =》 正则表达式  =》 匹配数据

# 正则表达式有多种 不同的语言使用的正则表达式都有区别  如：java perl python linux程序 sed gawk   mysql


# 正则表达式引擎是解释正则表达式的软件

# 正则表达式引擎 

# 1：POSIX 基本正则表达式（BRE）引擎
# 2：POSIX 扩展正则表达式（BRE）引擎 
