#!/bin/bash

# d命令删除模式空间中的当前行
# N 命令 和 d 命令同时使用时 要小心， 因为N合并两行为一行， 使用 d 命令 可能会删除2行
clear

sed '
N;
/developer\nkey/d
' test2

# sed 在单行上查找 developer 和 key，然后删除了两行


# 多行删除命令 ： D， 它删除模式空间中的第一行，它将删除至换行符的所有字符
sed '
N;
/developer\nkey/D
' test2
# 只会删除一行


echo
# 删除第一行前面的空行 先匹配空行，再与第二行合并，再使用D删除删除空行
echo '删除第一行前面的空行'
sed '/^$/{
N;
/1/D
}' test1

