#!/bin/bash

clear 

# 单行 next 命令

# n 命令告诉sed编辑器移动到数据流中文本的下一行，而不是回到命令的最开始
# 通常sed都是在单行上处理玩所有定义的命令后才移动到下一行

# example

# test1 有若干个空行  现在要删除第一个空行

# 下面命令会删除全部空行
sed '/^$/d' test1

echo 

# n 命令把处理的行往后移动一行， 就是找到 line 1 后面一行，然后删除
sed  '/line 1/{
n;
d
}' test1
 




